[package]
name = "todate"
version = "0.1.1"
edition = "2021"
description = "A utility to convert UNIX timestamps to human-readable dates."
license = "MIT"
repository = "https://github.com/PierreLeGuen/todate.git"

[dependencies]
chrono = "0.4.31"
